baseURL = "https://lmedez.github.io/Portfolio/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Lucian"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "blog"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Luciansoftware 2022"
footerLogo = "images/contact/luciansoftware-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo2.png"

[params.address]
address = "Cordoba, Argentina"
email = "luciano.sistemas.12@gmail.com"
openingHours = "Open to work all the time"
phone = "+(54) 3385 400249"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/luciano-menendez-536b351a2/"
weight = 2
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/LMedez"
weight = 4
